sonar.projectKey=aptlogica_sereni-antivirus-clamav
sonar.organization=aptlogica
sonar.sources=.
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.go.coverage.reportPaths=coverage.out
sonar.exclusions=Dockerfile,**/*_test.go