sonar.projectKey=aptlogica_sereni-antivirus-clamav_642069c8-96f6-4089-8d6c-753fca612286

sonar.language=go
sonar.sources=.
sonar.tests=tests
sonar.test.inclusions=**/*_test.go
sonar.go.coverage.reportPaths=coverage.out
sonar.exclusions=Dockerfile