sonar.projectKey=aptlogica_sereni-antivirus-clamav_642069c8-96f6-4089-8d6c-753fca612286

# Exclude Go test files and test folders
sonar.exclusions=**/*_test.go,**/test/**,**/tests/**,**/mock/**,**/mocks/**,sdk/**
 